name: Build app

on:
  # Run on each commit apart from docs updates
  push:
    paths-ignore:
    - 'abcdefg'
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: main
          ref: master

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          path: pages
          ref: gh-pages
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Build app
        run: |
          cd main
          npm ci
          npm run build
      
      - name: Commit all changes to repo
        run: |
          \rm -rfv /pages/
          \cp -r main/dist/** pages/
          cd pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update and build" -a
      
      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: pages
          branch: gh-pages
